name: CI

on:
  pull_request_target:
    branches:
      - default
  push:
    branches:
      - default
  release:
    types: published

jobs:
  #-----------------------------------------------------------------------------
  model-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: ["1.81.0", stable]

    name: Model: Test / ${{ matrix.os }} / Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Git commit info
        run: git log -n 1

      - name: Install Rust
        run: rustup install --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Run tests
        working-directory: model
        run: cargo test --verbose

  #-----------------------------------------------------------------------------
  model-quality:
    name: Model: Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup install --no-self-update stable && rustup default stable

      - name: Check formatting
        working-directory: model
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Lint with Clippy
        working-directory: model
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
